### ISSUE TITLE
dynamic imports have reached stage 4

### ISSUE THREAD

**Issue by cloud-walker** [DylanBob211/React-custom-setup#6]
https://github.com/DylanBob211/React-custom-setup/blob/2633f3b68836be17c69adedf3a1ebb9f29c99fe8/.babelrc#L7

You don't need a plugin anymore to transpile dynamic imports, as they have reached stage 4 and they are now supported directly by `@babel/preset-env`!

**Comment by DylanBob211** [comment]
the plugin has been removed
